# -*- coding: utf-8 -*-
"""speech to text.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rYGttgb4k4nHVqPaHqllI9u8eVsgYWHS
"""

!pip install git+https://github.com/openai/whisper.git

import whisper

# Load the small pretrained Whisper model
model = whisper.load_model("small")  # Options: tiny, base, small, medium, large

# Transcribe an audio file (must be .wav, .mp3, or .m4a)
result = model.transcribe("/content/harvard.wav")

# Print the transcription
print("Transcription:\n", result["text"])